### ISSUE TITLE
Add nunjucks example

### ISSUE THREAD

**Issue by jlongster** [ralyodio/express-template-demo#1]
Hey,

You can find code for integrating it here: http://nunjucks.jlongster.com/home#Express

It basically looks like this:

``` js
var nunjucks = require('nunjucks');
var express = require('express');

var env = new nunjucks.Environment(new nunjucks.FileSystemLoader('views'));
env.express(app);
```

You pass the path of your templates to the FileSystemLoader. You can ignore all the `app.set("views")` crap and other settings.

**Comment by ralyodio** [comment]
not sure how this will work with current app.js layout.
