### ISSUE TITLE
Dust template fails rendering

### ISSUE THREAD

**Issue by realpeterz** [ralyodio/express-template-demo#2]
500 Error: ENOENT, open '/Users/macbook/Downloads/express-template-demo/demo/views/views/layout.dust'

**Comment by ralyodio** [comment]
Just curious, did you run npm install?

**Comment by realpeterz** [comment]
Yes, I did. And I found the problem. it's the path in index.dust: {>"views/layout.dust"/} should be {>layout/} or {>layout.dust} because we are already in views directory.

**Comment by ralyodio** [comment]
weird. something must have changed, because i had to use the quoted version when I wrote it.

**Comment by VGraupera** [comment]
same thing here, and same fix by realpeterz works

**Comment by ralyodio** [comment]
Fixed.
